package constants;

import core.instances.SimpleMap;

public class Countries {
    private static final SimpleMap<String, String> countriesMap;

    static {
        countriesMap = new SimpleMap<>();

        countriesMap.put("AF", "Afghanistan");
        countriesMap.put("AL", "Albania");
        countriesMap.put("DZ", "Algeria");
        countriesMap.put("AD", "Andorra");
        countriesMap.put("AO", "Angola");
        countriesMap.put("AG", "Antigua and Barbuda");
        countriesMap.put("AR", "Argentina");
        countriesMap.put("AM", "Armenia");
        countriesMap.put("AU", "Australia");
        countriesMap.put("AT", "Austria");
        countriesMap.put("AZ", "Azerbaijan");
        countriesMap.put("BS", "Bahamas");
        countriesMap.put("BH", "Bahrain");
        countriesMap.put("BD", "Bangladesh");
        countriesMap.put("BB", "Barbados");
        countriesMap.put("BY", "Belarus");
        countriesMap.put("BE", "Belgium");
        countriesMap.put("BZ", "Belize");
        countriesMap.put("BJ", "Benin");
        countriesMap.put("BT", "Bhutan");
        countriesMap.put("BO", "Bolivia");
        countriesMap.put("BA", "Bosnia and Herzegovina");
        countriesMap.put("BW", "Botswana");
        countriesMap.put("BR", "Brazil");
        countriesMap.put("BN", "Brunei");
        countriesMap.put("BG", "Bulgaria");
        countriesMap.put("BF", "Burkina Faso");
        countriesMap.put("BI", "Burundi");
        countriesMap.put("CV", "Cabo Verde");
        countriesMap.put("KH", "Cambodia");
        countriesMap.put("CM", "Cameroon");
        countriesMap.put("CA", "Canada");
        countriesMap.put("CF", "Central African Republic");
        countriesMap.put("TD", "Chad");
        countriesMap.put("CL", "Chile");
        countriesMap.put("CN", "China");
        countriesMap.put("CO", "Colombia");
        countriesMap.put("KM", "Comoros");
        countriesMap.put("CG", "Congo");
        countriesMap.put("CD", "Congo, Democratic Republic of the");
        countriesMap.put("CR", "Costa Rica");
        countriesMap.put("HR", "Croatia");
        countriesMap.put("CU", "Cuba");
        countriesMap.put("CY", "Cyprus");
        countriesMap.put("CZ", "Czech Republic");
        countriesMap.put("DK", "Denmark");
        countriesMap.put("DJ", "Djibouti");
        countriesMap.put("DM", "Dominica");
        countriesMap.put("DO", "Dominican Republic");
        countriesMap.put("EC", "Ecuador");
        countriesMap.put("EG", "Egypt");
        countriesMap.put("SV", "El Salvador");
        countriesMap.put("GQ", "Equatorial Guinea");
        countriesMap.put("ER", "Eritrea");
        countriesMap.put("EE", "Estonia");
        countriesMap.put("SZ", "Eswatini");
        countriesMap.put("ET", "Ethiopia");
        countriesMap.put("FJ", "Fiji");
        countriesMap.put("FI", "Finland");
        countriesMap.put("FR", "France");
        countriesMap.put("GA", "Gabon");
        countriesMap.put("GM", "Gambia");
        countriesMap.put("GE", "Georgia");
        countriesMap.put("DE", "Germany");
        countriesMap.put("GH", "Ghana");
        countriesMap.put("GR", "Greece");
        countriesMap.put("GD", "Grenada");
        countriesMap.put("GT", "Guatemala");
        countriesMap.put("GN", "Guinea");
        countriesMap.put("GW", "Guinea-Bissau");
        countriesMap.put("GY", "Guyana");
        countriesMap.put("HT", "Haiti");
        countriesMap.put("HN", "Honduras");
        countriesMap.put("HU", "Hungary");
        countriesMap.put("IS", "Iceland");
        countriesMap.put("IN", "India");
        countriesMap.put("ID", "Indonesia");
        countriesMap.put("IR", "Iran");
        countriesMap.put("IQ", "Iraq");
        countriesMap.put("IE", "Ireland");
        countriesMap.put("IL", "Israel");
        countriesMap.put("IT", "Italy");
        countriesMap.put("JM", "Jamaica");
        countriesMap.put("JP", "Japan");
        countriesMap.put("JO", "Jordan");
        countriesMap.put("KZ", "Kazakhstan");
        countriesMap.put("KE", "Kenya");
        countriesMap.put("KI", "Kiribati");
        countriesMap.put("KP", "North Korea");
        countriesMap.put("KR", "South Korea");
        countriesMap.put("KW", "Kuwait");
        countriesMap.put("KG", "Kyrgyzstan");
        countriesMap.put("LA", "Laos");
        countriesMap.put("LV", "Latvia");
        countriesMap.put("LB", "Lebanon");
        countriesMap.put("LS", "Lesotho");
        countriesMap.put("LR", "Liberia");
        countriesMap.put("LY", "Libya");
        countriesMap.put("LI", "Liechtenstein");
        countriesMap.put("LT", "Lithuania");
        countriesMap.put("LU", "Luxembourg");
        countriesMap.put("MG", "Madagascar");
        countriesMap.put("MW", "Malawi");
        countriesMap.put("MY", "Malaysia");
        countriesMap.put("MV", "Maldives");
        countriesMap.put("ML", "Mali");
        countriesMap.put("MT", "Malta");
        countriesMap.put("MH", "Marshall Islands");
        countriesMap.put("MR", "Mauritania");
        countriesMap.put("MU", "Mauritius");
        countriesMap.put("MX", "Mexico");
        countriesMap.put("FM", "Micronesia");
        countriesMap.put("MD", "Moldova");
        countriesMap.put("MC", "Monaco");
        countriesMap.put("MN", "Mongolia");
        countriesMap.put("ME", "Montenegro");
        countriesMap.put("MA", "Morocco");
        countriesMap.put("MZ", "Mozambique");
        countriesMap.put("MM", "Myanmar");
        countriesMap.put("NA", "Namibia");
        countriesMap.put("NR", "Nauru");
        countriesMap.put("NP", "Nepal");
        countriesMap.put("NL", "Netherlands");
        countriesMap.put("NZ", "New Zealand");
        countriesMap.put("NI", "Nicaragua");
        countriesMap.put("NE", "Niger");
        countriesMap.put("NG", "Nigeria");
        countriesMap.put("MK", "North Macedonia");
        countriesMap.put("NO", "Norway");
        countriesMap.put("OM", "Oman");
        countriesMap.put("PK", "Pakistan");
        countriesMap.put("PW", "Palau");
        countriesMap.put("PS", "Palestine");
        countriesMap.put("PA", "Panama");
        countriesMap.put("PG", "Papua New Guinea");
        countriesMap.put("PY", "Paraguay");
        countriesMap.put("PE", "Peru");
        countriesMap.put("PH", "Philippines");
        countriesMap.put("PL", "Poland");
        countriesMap.put("PT", "Portugal");
        countriesMap.put("QA", "Qatar");
        countriesMap.put("RO", "Romania");
        countriesMap.put("RU", "Russia");
        countriesMap.put("RW", "Rwanda");
        countriesMap.put("KN", "Saint Kitts and Nevis");
        countriesMap.put("LC", "Saint Lucia");
        countriesMap.put("VC", "Saint Vincent and the Grenadines");
        countriesMap.put("WS", "Samoa");
        countriesMap.put("SM", "San Marino");
        countriesMap.put("ST", "Sao Tome and Principe");
        countriesMap.put("SA", "Saudi Arabia");
        countriesMap.put("SN", "Senegal");
        countriesMap.put("RS", "Serbia");
        countriesMap.put("SC", "Seychelles");
        countriesMap.put("SL", "Sierra Leone");
        countriesMap.put("SG", "Singapore");
        countriesMap.put("SK", "Slovakia");
        countriesMap.put("SI", "Slovenia");
        countriesMap.put("SB", "Solomon Islands");
        countriesMap.put("SO", "Somalia");
        countriesMap.put("ZA", "South Africa");
        countriesMap.put("SS", "South Sudan");
        countriesMap.put("ES", "Spain");
        countriesMap.put("LK", "Sri Lanka");
        countriesMap.put("SD", "Sudan");
        countriesMap.put("SR", "Suriname");
        countriesMap.put("SE", "Sweden");
        countriesMap.put("CH", "Switzerland");
        countriesMap.put("SY", "Syria");
        countriesMap.put("TJ", "Tajikistan");
        countriesMap.put("TZ", "Tanzania");
        countriesMap.put("TH", "Thailand");
        countriesMap.put("TL", "Timor-Leste");
        countriesMap.put("TG", "Togo");
        countriesMap.put("TO", "Tonga");
        countriesMap.put("TT", "Trinidad and Tobago");
        countriesMap.put("TN", "Tunisia");
        countriesMap.put("TR", "Turkey");
        countriesMap.put("TM", "Turkmenistan");
        countriesMap.put("TV", "Tuvalu");
        countriesMap.put("UG", "Uganda");
        countriesMap.put("UA", "Ukraine");
        countriesMap.put("AE", "United Arab Emirates");
        countriesMap.put("GB", "United Kingdom");
        countriesMap.put("US", "United States");
        countriesMap.put("UY", "Uruguay");
        countriesMap.put("UZ", "Uzbekistan");
        countriesMap.put("VU", "Vanuatu");
        countriesMap.put("VE", "Venezuela");
        countriesMap.put("VN", "Vietnam");
        countriesMap.put("YE", "Yemen");
        countriesMap.put("ZM", "Zambia");
        countriesMap.put("ZW", "Zimbabwe");
    }

    public static String getCountryName(String code) {
        if (code == null) {
            return null;
        }

        return countriesMap.get(code.toUpperCase());
    }
}
